name: Crystal CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image: crystallang/crystal:1.0.0

    steps:
    - uses: actions/checkout@v1
    - name: Crystal Ameba Linter
      id: crystal-ameba
      uses: crystal-ameba/github-action@v0.2.12
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Install dependencies
      run: shards install

    - name: Check format
      run: crystal tool format --check

    - name: Run tests
      env:
        KEMAL_ENV: test
      run: crystal spec

    - name: Create test  dummy
      run: echo 'require "./spec/**"' > run_tests.cr && crystal build run_tests.cr -D skip-integration

    - name: Coverage
      uses: sudo-bot/action-kcov@latest
      with:
        cli-args: --clean --include-path=$(pwd)/src ./run_tests

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        directory: ./coverage
        flags: spec
      if: ${{ always() }}